name: Deploy Staging

on:
  push:
    branches:
      - staging
    paths:
      - "dinver-backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Kamal
        run: gem install kamal -v ">= 2, < 3"

      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}

      - name: Configure SSH Host Checking
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          cat > ~/.ssh/config <<'EOF'
          Host *
            StrictHostKeyChecking accept-new
            UserKnownHostsFile ~/.ssh/known_hosts
          EOF
          chmod 600 ~/.ssh/config

      - name: Run Kamal Deploy
        env:
          DOTENV_PRIVATE_KEY_STAGING: ${{ secrets.DOTENV_PRIVATE_KEY_STAGING }}
          DOCKER_BUILDKIT: 1
        run: cd dinver-backend && kamal deploy -d staging