name: Deploy Applications

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          node-version: "18"
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy Backend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          echo "machine api.heroku.com" > ~/.netrc
          echo "  login $HEROKU_EMAIL" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          echo "machine git.heroku.com" >> ~/.netrc
          echo "  login $HEROKU_EMAIL" >> ~/.netrc
          echo "  password $HEROKU_API_KEY" >> ~/.netrc
          heroku git:remote -a dinver-backend
          git subtree split --prefix dinver-backend -b heroku-deploy
          git push heroku heroku-deploy:main --force

  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Dependencies and Build Frontends
        run: |
          cd dinver-frontend && npm install && npm run build
          cd ../admin-frontend && npm install && npm run build
          cd ../sysadmin-frontend && npm install && npm run build
      - name: Deploy Frontends to Hostinger
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          # Deploy dinver-frontend
          lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "
            mirror -R ./dinver-frontend/build /public_html;
            bye
          "
          # Deploy admin-frontend
          lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "
            mirror -R ./admin-frontend/build /admin;
            bye
          "
          # Deploy sysadmin-frontend
          lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "
            mirror -R ./sysadmin-frontend/build /sysadmin;
            bye
          "
